pipeline {
    agent any

    stages {
        stage('Unit tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                GOCACHE = '/tmp/go-cache'
                GOPATH = '/tmp/go-path'
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'GOCACHE=/tmp/go-cache go test -v ./...'
                }
            }
        }

        stage('Unit Tests  - FE') {
            agent {
                docker {
                    image 'node:20'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                      npm ci
                      npm test  
                    '''
                }
            }
        }
    }
}
