pipeline {
    agent any

    stages {
        stage('Unit tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                GOCACHE = '/tmp/go-cache'
                GOPATH = '/tmp/go-path'
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'GOCACHE=/tmp/go-cache go test -v ./... 2>&1 | go-junit-report > test-results.xml'
                }
            }
            post {
                always {
                    junit 'bugtracker-backend/test-results.xml'
                }
            }
        }

        stage('Unit Tests  - FE') {
            agent {
                docker {
                    image 'node:20'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                      npm ci
                      npm test  
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }
    }
}
