name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

  jobs:
    unit-tests-be:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v4
          with: 
            go-version: "1.21"
            cache-dependency-path: bugtracker-backend/go.sum

        - name: Execute BE Unit tests
          working-drectory: ./bugtracker-backend
          run: |
            go test -v ./...
